# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://daily.baty.net/"
title = "Jack Baty Daily"
enableRobotsTXT = true
enableEmoji = true
# theme = "daily-jane" (this is now a hugo module)

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 30              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname (baty)
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓


# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
languageCode = "en-US"

[author]                  # essential                     # 必需
  name = "Jack Baty"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]             # config your menu              # 配置目录
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Calendar"
  weight = 25
  identifier = "calendar"
  url = "/calendar/"
[[menu.main]]
  name = "Archives"
  weight = 30
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Wiki"
  weight = 50
  url = "https://wiki.baty.net"
[[menu.main]]
  name = "Blog"
  weight = 60
  url = "https://baty.net/"


[params]
  since = "2021"            # Site creation time          # 站点建立时间
  homeFullContent = true   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Jack Baty Daily"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Photography", "Writing","Emacs"]
  description = "I already spent the money"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "January 2, 2006"
  dateFormatToUseArchives = "2006-01-02"
  dateFormatToUseTaxonomy = "2006-01-02"

  showAuthorInfo = true # show author info below the article


  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 300

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  paginateOriginalStyle = true




  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = false
  # contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['custom.js']             # if ['custom.js'], load '/static/js/custom.js' file


  [params.social]                                         # 社交链接
    a-email = "mailto:jack@baty.net"
    b-stack-overflow = ""
    c-twitter = ""
    d-facebook = ""
    e-linkedin = ""
    f-google = ""
    g-github = "https://github.com/jackbaty"
    h-weibo = ""
    i-zhihu = ""
    j-douban = ""
    k-pocket = ""
    l-tumblr = ""
    m-instagram = ""
    n-gitlab = ""
    o-goodreads = ""
    p-coding = ""
    q-bilibili = ""
    r-codeforces = ""
    s-mastodon = "https://social.baty.net/@jack"
    t-youtube = ""
    u-twitch = ""
    v-flickr = "https://flickr.com/photos/jbaty"

  [params.commento] # Commento is a feature rich lightweight comment system oriented on privacy (https://commento.io/)
    enable = false
    url = "https://comments.baty.net"



[permalinks]
post = "/:year:/:slug/"

# adding taxonomy term 'archive'
[taxonomies]
    archive = "archive"

# allow HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[module.imports]]
  path = "github.com/jackbaty/daily-jane"
  # theme

